### ISSUE TITLE
Use Exception Class for Pyinseq specific errors

### ISSUE THREAD

**Issue by eburgoswisc** [mjmlab/pyinseq#74]
Many errors that Pyinseq outputs are specific to the computational workflow. To aid in debugging and development, a separate python class should be written that will inherit from Exception.

**Comment by mandel01** [comment]
Can you list some examples?

**Comment by eburgoswisc** [comment]
1. When there is a directory with the experimental name.
2. If any file (fastq, fasta, genbank...) are not found. (FileNotFound can work but a custom Exception can inherit from this)
3. If text file does not have proper barcodes (Barcode exception?).
4. If alignments were not made. (I had test cases where output files were completely empty, still deciding if that should be an exception, maybe warning?)

Maybe more, I thought this recently so not many ideas yet...

**Comment by mandel01** [comment]
I'm closing this since no specific action is needed. Feel free to work on this in the future.
