### ISSUE TITLE
Bug in PyPi project description

### ISSUE THREAD

**Issue by eburgoswisc** [mjmlab/pyinseq#82]
Pyinseq 0.3.0 on Pypi has a bug in its project description that does not allow the logo to render properly. To fix this, the README should have a link that points to the Github repository's image which allows PyPi to find it. This fix should be included in pyinseq 0.3.1 including the removal of the disclaimer since it should be available on bioconda. Otherwise, this new version of the program will work just fine.

**Comment by mandel01** [comment]
Does the image issue carry over to the bioconda docs? (I.e. do we want to fix this before adding to bioconda)?

**Comment by eburgoswisc** [comment]
Bioconda docs just uses the meta.yml file for the package page, it does not carry over any other info. There will be links that point to the README in github.

**Comment by eburgoswisc** [comment]
The bug was fixed in release 0.3.1 of pyinseq, issue is resolved.
